### ISSUE TITLE
Application Development Roadmap

### ISSUE THREAD

**Issue by micahbule** [carreoniverse/SchedChurch#1]
## Minimum Viable Product (MVP)
For you final project, I would be requiring you to develop the following features based on the [list](https://github.com/carreoniverse/SchedChurch/blob/master/README.md) you pushed in this repository:

- [ ] User login for both Admin and Guests
- [ ] As a guest, a user should be able to make new reservations
- [ ] As a guest, a user should be able to update existing reservations, including editing of reservation information, submission of requirements, and canceling the reservation itself
- [ ] As an admin, a user should be able to view, approve, or decline pending reservations

_Note: All of the above are under the assumption that both users have an access to a calendar view for the requests_

## Next Critical Features
The following features are critical for your application such that after the MVP, these would be the next necessary features to be developed:

- [ ] Ability for the admin to add church-hosted events such as regular and special mass schedule, as well as community events (ex. feeding programs, etc.)

## Nice-2-Haves (N2Hs)
These features are not that necessary for your application to run smoothly, but they are definitely nice to have if you can throw them in:

- [ ] Reports (Monthly report of all events, monthly income report from events, etc.)

## Unmentioned feature?
Any other features in your list not mentioned in this issue are either vague or is left for the developers to decide whether to include it or not.
